# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('care_id', models.AutoField(primary_key=True, serialize=False)),
                ('care_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('care_way', models.CharField(blank=True, max_length=50, null=True)),
                ('care_time', models.DateTimeField()),
                ('care_remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('care_nexttime', models.DateTimeField()),
                ('care_people', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_care',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_qq', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('customer_job', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_blog', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_msn', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_day', models.DateTimeField()),
                ('customer_addtime', models.DateTimeField()),
                ('customer_addman', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_changtime', models.DateTimeField()),
                ('change_man', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_company', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerLinkman',
            fields=[
                ('linkman_id', models.AutoField(primary_key=True, serialize=False)),
                ('linkman_name', models.CharField(blank=True, max_length=50, null=True)),
                ('linkman_sex', models.CharField(blank=True, max_length=20, null=True)),
                ('linkman_job', models.CharField(blank=True, max_length=100, null=True)),
                ('linkman_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('linkman_age', models.IntegerField(blank=True, null=True)),
                ('linkman_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_linkman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerLinkreord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_time', models.DateTimeField()),
                ('who_link', models.CharField(blank=True, max_length=50, null=True)),
                ('link_type', models.CharField(blank=True, max_length=50, null=True)),
                ('link_theme', models.CharField(blank=True, max_length=200, null=True)),
                ('link_nexttime', models.DateTimeField()),
                ('link_remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_linkreord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerSource',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status_explain', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'department_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('email_time', models.DateTimeField()),
                ('email_state', models.CharField(blank=True, max_length=50, null=True)),
                ('email_theme', models.CharField(blank=True, max_length=200, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'email_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_address', models.CharField(blank=True, max_length=500, null=True)),
                ('house_price', models.IntegerField(blank=True, null=True)),
                ('house_ambient', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'house_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'house_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeInfo',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_item', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_content', models.CharField(blank=True, max_length=2000, null=True)),
                ('notice_time', models.DateTimeField()),
                ('notice_endtime', models.DateTimeField()),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'notice_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('user_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(blank=True, max_length=500, null=True)),
                ('user_num', models.CharField(blank=True, max_length=100, null=True)),
                ('user_pw', models.CharField(blank=True, max_length=50, null=True)),
                ('user_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('user_idnum', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_addtime', models.DateTimeField()),
                ('user_addman', models.CharField(blank=True, max_length=50, null=True)),
                ('user_changetime', models.DateTimeField()),
                ('user_changeman', models.CharField(blank=True, max_length=50, null=True)),
                ('user_intest', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_diploma', models.CharField(blank=True, max_length=20, null=True)),
                ('user_bankcard', models.CharField(blank=True, max_length=20, null=True)),
                ('user_nation', models.CharField(blank=True, max_length=20, null=True)),
                ('is_married', models.CharField(blank=True, max_length=10, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
                ('role_power', models.IntegerField(blank=True, null=True)),
                ('is_used', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
    ]
